# Generated by Django 3.2.8 on 2022-10-22 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_post_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='community_ids',
        ),
        migrations.RemoveField(
            model_name='users',
            name='follower_ids',
        ),
        migrations.RemoveField(
            model_name='users',
            name='following_ids',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
        migrations.CreateModel(
            name='UserFollowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.IntegerField(blank=True)),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'UserFollowers',
            },
        ),
    ]
