# Generated by Django 3.2.8 on 2022-10-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221022_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowers',
            old_name='user_id',
            new_name='user',
        ),
    ]
