# Generated by Django 3.2.8 on 2022-10-23 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_comments_communities_posts_topics_usercommunity_usertopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.posts'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='thread_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='country_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='location',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
