# Generated by Django 3.2.8 on 2022-10-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20221023_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='isNestedComment',
            field=models.BooleanField(default=False),
        ),
    ]
