# Generated by Django 3.2.8 on 2022-10-23 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_comments_isnestedcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parentComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.comments'),
        ),
    ]
